### ISSUE TITLE
gyp error when npm install 

### ISSUE THREAD

**Issue by lhf552004** [wavded/io-barcode#11]
Hi, thank you for your io-barcode, but when I install it with npm, there is warn and error happened,
It seems installed at my project, Is it OK? or something wrong. 

> canvas@1.4.0 install /home/pi/projects/FLCos/node_modules/io-barcode/node_modules/canvas-browserify/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error:`gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/pi/.nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-327.el7.x86_64
gyp ERR! command "/home/pi/.nvm/versions/node/v4.4.7/bin/node" "/home/pi/.nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/projects/FLCos/node_modules/io-barcode/node_modules/canvas-browserify/node_modules/canvas
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing canvas@1.4.0
io-barcode@1.3.0 node_modules/io-barcode
├── babel-runtime@6.11.6 (regenerator-runtime@0.9.5)
├── core-js@2.4.1
└── canvas-browserify@1.1.3

**Comment by wavded** [comment]
You need the libcairo or cairo-dev packages depending on your system for node-canvas support.  See:

https://github.com/Automattic/node-canvas#installation
