### ISSUE TITLE
Export canvas as Base64

### ISSUE THREAD

**Issue by igorissen** [wavded/io-barcode#5]
On the server side I want to create the barcode and return to the client a base64 representation of the barcode so that it can be used on `<img />` tab `src` attribute.

**Comment by wavded** [comment]
@igorissen you get a [node-canvas](https://github.com/Automattic/node-canvas) object on the server back, it includes a `canvas.toDataURL()` which will get you the base64 data uri you can put right into an `<img />` tag.  Hope that helps.

**Comment by igorissen** [comment]
Great. I didn't go to node-canvas documentation, sorry about that. Thank you.
