### ISSUE TITLE
Check barcode type

### ISSUE THREAD

**Issue by igorissen** [wavded/io-barcode#6]
Hi,

is there a function in the module to check the type of a barcode ? Before creating a specific barcode canvas I want to check the type of the barcode and his validity.

Thanks

**Comment by wavded** [comment]
There currently is anything exposed by the API for you to check that, but it is checked... see:

https://github.com/wavded/io-barcode/blob/isomorphic/modules/index.js#L54

An error will be thrown if it isn't valid that you can catch.

**Comment by wavded** [comment]
Closing due to length open, feel free to still discuss.
